### ISSUE TITLE
The application can send emails

### ISSUE THREAD

**Issue by Pcushing** [Pcushing/pycky#11]
Since we're on the topic, let's get this set up now rather than later. I'm adding authentication now and it'd be nice to have so we can do email confirmation right away.

We'll need to use some service to send emails. In the past I've used Sendgrid (~$10/m) but I used Amazon SES in a recently project, which was easy and apparently super cheap ($0.10 per 1K emails): https://aws.amazon.com/ses/pricing/. I'd advocate that for now. You can always switch later if it ends up not scaling well price-wise.

To get this set up, I'll need you to set up an Amazon AWS account: https://aws.amazon.com/ses/. I havent set up an account for just this before so if you hit a point that you're confused, send me the credentials. Just make sure you've added a credit card for charges so you dont need to share that info w/ me.

I'll also need access to your domain provider (GoDaddy, Namecheap, or wherever else you purchased pycky.com) so I can configure emails to work with your pycky.com domain.

When you're done, update this ticket and you can assign to me and remove yourself.

**Comment by Pcushing** [comment]
Also, I'll add the question label:

![image](https://user-images.githubusercontent.com/47611/31359976-1ec7802a-ad01-11e7-8001-50bfa1bbf01c.png)

for anything where I need your input before moving forward. This'll come up all the time so it'll help organize where you can dive in to support as we go.

**Comment by Pycky** [comment]
The domain information for pycky.com is on the trello page - I know Sean
had that stuff organized - Let me know if you can't find it.

For the AWS the domain name Pycky already exists? Can you ask Sean some of
these questions to make sure we aren't overlapping with things he has
already done? His email is seanppryor@gmail.com.

Antigone
[image: Inline image 1]

**Comment by Pcushing** [comment]
Thanks for pointing me to Trello. I forgot that I saw some of this in here before. I have everything I need, but I'll sync with Sean, regardless.

I'm going to put in a couple more hours on this today, and then I'm unavailable until mid-to-late next week when I'll start getting on more of a weekly Thurs/Fri schedule with this.
